// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LocateFolder
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidLocateFolderCmdPackageString = "a3dc7eb8-9500-4313-9e35-e3c7878114ec";
        public const string guidLocateFolderCmdPackageCmdSetString = "4b1b60f4-3cf6-42c9-b1e5-dc2931e5cb3a";
        public const string guidImagesString = "1e2defd0-1ace-4664-b110-b3e180af43e0";
        public static Guid guidLocateFolderCmdPackage = new Guid(guidLocateFolderCmdPackageString);
        public static Guid guidLocateFolderCmdPackageCmdSet = new Guid(guidLocateFolderCmdPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int LocateFolderCmdId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
