// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LocateFolder
{
  static class Vsix
  {
    public const string Id = "48d3bf5a-f247-4587-ab35-d47a1aff2add";
    public const string Name = "LocateFolder";
    public const string Description = @"Locate Files and Fiolders in Windows Explorer";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Edgar Knapp";
    public const string Tags = "";
  }
}
